"""Market-data fetchers: SPX options chain, daily SPX/VIX history, FRED rates.

Design philosophy — **live with a deterministic offline fallback.**  Every public
``get_*`` helper first attempts a live pull (yfinance / FRED).  If the network, the
dependency, or the returned payload is unavailable or malformed, it falls back to a
*deterministic, seeded synthetic* generator so the entire research stack — calibration,
regime detection, the API — runs end-to-end with no network access.  Each result carries
a :class:`FetchResult.source` flag (``"live"`` / ``"synthetic"``) and an ``as_of``
timestamp so callers (and the API's staleness logic) always know what they are holding.

Public surface
--------------
    get_market_snapshot(config)      -> ChainSnapshot   # spot + rate + options chain
    get_price_history(config)        -> FetchResult[pd.DataFrame]
    get_vix_term_structure(config)   -> FetchResult[pd.DataFrame]
    get_risk_free_rate(config)       -> float
    filter_liquid_options(chain, cfg)-> (pd.DataFrame, LiquidityReport)

The synthetic price history is generated by a 3-regime volatility Markov chain, which is
what makes the downstream HMM recover *economically meaningful* regimes (calm / elevated
/ crisis) even offline.
"""

from __future__ import annotations

import os
from concurrent.futures import ThreadPoolExecutor
from concurrent.futures import TimeoutError as FuturesTimeout
from dataclasses import dataclass
from datetime import datetime, timezone

import numpy as np
import pandas as pd

from models.black_scholes import bs_price, implied_vol
from models.heston import HestonParams, heston_price


class DataUnavailable(RuntimeError):
    """Raised by the live-only fetchers when a live pull cannot be completed."""


@dataclass
class FetchResult:
    """A fetched dataset plus provenance.

    Attributes
    ----------
    data : Any
        The payload (a ``DataFrame``, ``Series`` or scalar).
    source : {"live", "synthetic"}
        Whether the data came from the network or the deterministic fallback.
    as_of : datetime
        UTC timestamp the data was produced/observed.
    symbol : str
        The instrument identifier, for diagnostics.
    """

    data: object
    source: str
    as_of: datetime
    symbol: str = ""


@dataclass
class ChainSnapshot:
    """A single-instant options snapshot, the unit calibration consumes.

    ``chain`` is a tidy DataFrame with one row per quoted option and the canonical
    columns produced by both the live and synthetic paths:
    ``expiry, maturity, strike, option_type, bid, ask, mid, last, volume,
    open_interest, market_iv``.
    """

    spot: float
    rate: float
    div_yield: float
    chain: pd.DataFrame
    source: str
    as_of: datetime


@dataclass
class LiquidityReport:
    """Counts of options removed by each liquidity filter, for diagnostics."""

    n_input: int
    n_kept: int
    removed_deep_otm: int = 0
    removed_zero_oi: int = 0
    removed_wide_spread: int = 0
    removed_short_maturity: int = 0
    removed_no_iv: int = 0

    def as_dict(self) -> dict:
        return {
            "n_input": self.n_input,
            "n_kept": self.n_kept,
            "removed_deep_otm": self.removed_deep_otm,
            "removed_zero_oi": self.removed_zero_oi,
            "removed_wide_spread": self.removed_wide_spread,
            "removed_short_maturity": self.removed_short_maturity,
            "removed_no_iv": self.removed_no_iv,
        }


CHAIN_COLUMNS = [
    "expiry",
    "maturity",
    "strike",
    "option_type",
    "bid",
    "ask",
    "mid",
    "last",
    "volume",
    "open_interest",
    "market_iv",
]


def _now() -> datetime:
    return datetime.now(timezone.utc)


# Bounded pool so a slow yfinance/FRED call can be abandoned via a timeout instead of
# hanging a request. The orphaned thread finishes in the background; we just stop waiting.
_EXECUTOR = ThreadPoolExecutor(max_workers=4, thread_name_prefix="hrl-fetch")


def _request_timeout(config: dict) -> float:
    timeout = float(config.get("data", {}).get("request_timeout", 8.0))
    if not np.isfinite(timeout) or timeout <= 0.0:
        raise ValueError(f"data.request_timeout must be finite and > 0, got {timeout!r}")
    return timeout


def _call_with_timeout(timeout: float, fn, *args, **kwargs):
    """Run a blocking live fetch with a hard timeout; raise DataUnavailable if it elapses."""
    future = _EXECUTOR.submit(fn, *args, **kwargs)
    try:
        return future.result(timeout=timeout)
    except FuturesTimeout as exc:
        future.cancel()
        raise DataUnavailable(f"live fetch timed out after {timeout:.0f}s") from exc


# --------------------------------------------------------------------------- #
# Live fetchers (yfinance / FRED).  Each raises DataUnavailable on any failure. #
# --------------------------------------------------------------------------- #


def fetch_price_history_live(ticker: str, years: int) -> pd.DataFrame:
    """Daily OHLCV history via yfinance, normalised to ``[close, volume]``.

    Raises
    ------
    DataUnavailable
        On import failure, network error, or an empty/malformed frame.
    """
    try:
        import yfinance as yf

        period = f"{int(years)}y"
        raw = yf.Ticker(ticker).history(period=period, auto_adjust=True)
        if raw is None or raw.empty or "Close" not in raw.columns:
            raise DataUnavailable(f"empty history for {ticker}")
        df = pd.DataFrame(
            {
                "close": raw["Close"].astype(float),
                "volume": raw.get("Volume", pd.Series(index=raw.index, dtype=float)).astype(float),
            }
        )
        df.index = pd.to_datetime(df.index).tz_localize(None)
        df = df.dropna(subset=["close"])
        if len(df) < 252:
            raise DataUnavailable(f"history too short for {ticker}: {len(df)} rows")
        return df
    except DataUnavailable:
        raise
    except Exception as exc:  # noqa: BLE001 — any failure routes to the fallback
        raise DataUnavailable(f"price-history fetch failed for {ticker}: {exc}") from exc


def fetch_spot_live(ticker: str) -> float:
    """Latest adjusted close via a small download suitable for request-time snapshots."""
    try:
        import yfinance as yf

        raw = yf.Ticker(ticker).history(period="5d", auto_adjust=True)
        if raw is None or raw.empty or "Close" not in raw.columns:
            raise DataUnavailable(f"no recent close for {ticker}")
        close = pd.to_numeric(raw["Close"], errors="coerce").dropna()
        if close.empty or not np.isfinite(close.iloc[-1]) or close.iloc[-1] <= 0.0:
            raise DataUnavailable(f"invalid recent close for {ticker}")
        return float(close.iloc[-1])
    except DataUnavailable:
        raise
    except Exception as exc:  # noqa: BLE001
        raise DataUnavailable(f"spot fetch failed for {ticker}: {exc}") from exc


def fetch_vix_term_structure_live(tickers: dict, years: int) -> pd.DataFrame:
    """VIX term structure (9d / 30d / 3m close) via yfinance, aligned by date."""
    try:
        import yfinance as yf

        period = f"{int(years)}y"
        cols = {}
        for name, sym in tickers.items():
            raw = yf.Ticker(sym).history(period=period, auto_adjust=False)
            if raw is None or raw.empty or "Close" not in raw.columns:
                raise DataUnavailable(f"empty VIX series {sym}")
            s = raw["Close"].astype(float)
            s.index = pd.to_datetime(s.index).tz_localize(None)
            cols[name] = s
        df = pd.DataFrame(cols).dropna(how="all")
        if df.empty:
            raise DataUnavailable("VIX term structure empty after align")
        return df
    except DataUnavailable:
        raise
    except Exception as exc:  # noqa: BLE001
        raise DataUnavailable(f"VIX fetch failed: {exc}") from exc


def fetch_fred_rate_live(series_id: str, api_key: str | None) -> float:
    """Latest FRED rate observation (percent -> decimal), e.g. DGS3MO."""
    if not api_key:
        raise DataUnavailable("no FRED API key configured")
    try:
        from fredapi import Fred

        s = Fred(api_key=api_key).get_series(series_id).dropna()
        if s.empty:
            raise DataUnavailable(f"FRED series {series_id} empty")
        return float(s.iloc[-1]) / 100.0
    except DataUnavailable:
        raise
    except Exception as exc:  # noqa: BLE001
        raise DataUnavailable(f"FRED fetch failed for {series_id}: {exc}") from exc


def fetch_options_chain_live(
    underlying: str,
    spot: float,
    rate: float,
    div_yield: float,
    today: datetime,
    max_expiries: int | None = None,
    target_days: tuple[int, ...] = (30, 90, 180, 365),
) -> pd.DataFrame:
    """Full options chain via yfinance, normalised to :data:`CHAIN_COLUMNS`.

    yfinance returns one calls/puts frame per expiry; we concatenate across expiries,
    drop rows with no usable bid/ask, recompute the *mid* and our own Black-Scholes
    implied vol from the mid (yfinance's ``impliedVolatility`` is unreliable), and
    compute time-to-maturity in years.
    """
    try:
        import yfinance as yf

        tk = yf.Ticker(underlying)
        expiries = list(tk.options)
        if not expiries:
            raise DataUnavailable(f"no expiries for {underlying}")
        if max_expiries is not None:
            if max_expiries < 1:
                raise ValueError("max_expiries must be >= 1")
            today_date = pd.Timestamp(today.date())
            future = [exp for exp in expiries if (pd.to_datetime(exp) - today_date).days > 0]
            # Select representative tenors instead of the first N weeklies.  A bounded
            # chain is much more likely to finish inside the API request timeout while
            # retaining enough maturity coverage for calibration.
            selected: list[str] = []
            for target in target_days:
                candidates = [exp for exp in future if exp not in selected]
                if not candidates or len(selected) >= max_expiries:
                    break
                selected.append(
                    min(
                        candidates,
                        key=lambda exp: abs((pd.to_datetime(exp) - today_date).days - target),
                    )
                )
            if len(selected) < max_expiries:
                selected.extend(exp for exp in future if exp not in selected)
            expiries = selected[:max_expiries]
        rows = []
        for exp in expiries:
            try:
                oc = tk.option_chain(exp)
            except Exception:  # noqa: BLE001 — skip a malformed single expiry
                continue
            exp_dt = pd.to_datetime(exp)
            tau = max((exp_dt - pd.Timestamp(today.date())).days, 0) / 365.0
            if tau <= 0:
                continue
            for df, otype in ((oc.calls, "call"), (oc.puts, "put")):
                if df is None or df.empty:
                    continue
                part = df.copy()
                part["option_type"] = otype
                part["expiry"] = exp_dt
                part["maturity"] = tau
                rows.append(part)
        if not rows:
            raise DataUnavailable(f"all expiries malformed for {underlying}")
        raw = pd.concat(rows, ignore_index=True)
        return _normalise_live_chain(raw, spot, rate, div_yield)
    except DataUnavailable:
        raise
    except Exception as exc:  # noqa: BLE001
        raise DataUnavailable(f"options fetch failed for {underlying}: {exc}") from exc


def _normalise_live_chain(
    raw: pd.DataFrame, spot: float, rate: float, div_yield: float
) -> pd.DataFrame:
    """Coerce a raw yfinance chain into the canonical schema, tolerating gaps."""

    def numeric(name: str, default: float = np.nan) -> pd.Series:
        values = raw[name] if name in raw.columns else pd.Series(default, index=raw.index)
        return pd.to_numeric(values, errors="coerce")

    out = pd.DataFrame(index=raw.index)
    out["expiry"] = raw["expiry"]
    out["maturity"] = raw["maturity"].astype(float)
    out["strike"] = numeric("strike")
    out["option_type"] = raw["option_type"]
    out["bid"] = numeric("bid")
    out["ask"] = numeric("ask")
    out["last"] = numeric("lastPrice")
    out["volume"] = numeric("volume", 0.0).fillna(0.0)
    out["open_interest"] = numeric("openInterest", 0.0).fillna(0.0)

    # Mid from a valid, non-crossed bid/ask pair; otherwise fall back to last trade.
    mid = (out["bid"] + out["ask"]) / 2.0
    valid_market = (out["bid"] > 0) & (out["ask"] >= out["bid"])
    mid = mid.where(valid_market, out["last"])
    out["mid"] = mid

    # Drop structurally unusable rows (no strike, no price).
    out = out.dropna(subset=["strike", "maturity"])
    out = out[(out["strike"] > 0) & (out["maturity"] > 0) & (out["mid"] > 0)]

    # Our own BS implied vol from the mid — the project's canonical price->IV map.
    out["market_iv"] = [
        implied_vol(float(m), spot, float(k), rate, div_yield, float(t), ot)
        for m, k, t, ot in zip(out["mid"], out["strike"], out["maturity"], out["option_type"])
    ]
    return out[CHAIN_COLUMNS].reset_index(drop=True)


# --------------------------------------------------------------------------- #
# Deterministic synthetic fallback                                             #
# --------------------------------------------------------------------------- #
#
# The fallback must be *realistic enough* that downstream consumers behave as they
# would on real data: an arbitrage-light vol surface with a smile/skew for
# calibration, and a 3-regime price/VIX history for the HMM.

# Plausible SPX-like Heston parameters used to synthesise the offline vol surface.
_SYN_HESTON = HestonParams(kappa=2.5, theta=0.04, sigma=0.6, rho=-0.7, v0=0.035)


def synthetic_options_chain(
    config: dict, spot: float, rate: float, div_yield: float, today: datetime
) -> pd.DataFrame:
    """A deterministic Heston-generated vol surface in the canonical chain schema.

    Prices come from :data:`_SYN_HESTON`; bid/ask straddle the mid by a fixed relative
    half-spread; market IV is recovered from the mid by the same BS inversion used on
    live data, so the offline calibration target is self-consistent.
    """
    syn = config["data"]["synthetic_fallback"]
    rng = np.random.default_rng(int(syn["seed"]))
    n_k = int(syn["n_strikes"])
    n_t = int(syn["n_maturities"])
    half_spread = float(syn["rel_spread"])
    perturb = float(syn.get("smile_perturb", 0.0))
    if n_k < 2 or n_t < 1:
        raise ValueError("synthetic fallback requires n_strikes >= 2 and n_maturities >= 1")
    if not 0.0 <= half_spread < 1.0:
        raise ValueError("synthetic rel_spread must satisfy 0 <= rel_spread < 1")

    moneyness = np.linspace(0.80, 1.20, n_k)
    strikes = np.round(spot * moneyness, 0)
    standard_days = np.array([7, 30, 60, 90, 180, 365], dtype=float)
    if n_t <= standard_days.size:
        maturity_days = standard_days[:n_t]
    else:
        maturity_days = np.unique(np.round(np.geomspace(7, 730, n_t))).astype(float)
        if maturity_days.size != n_t:
            raise ValueError("n_maturities is too large to create distinct day tenors")
    maturities = maturity_days / 365.0

    rows = []
    for tau in maturities:
        forward = spot * np.exp((rate - div_yield) * tau)
        expiry = pd.Timestamp(today.date()) + pd.Timedelta(days=int(round(tau * 365)))
        for k in strikes:
            otype = "put" if k < forward else "call"  # quote the liquid OTM leg
            heston_p = float(
                heston_price(_SYN_HESTON, spot, float(k), rate, div_yield, float(tau), otype)
            )
            base_iv = implied_vol(heston_p, spot, float(k), rate, div_yield, float(tau), otype)
            # A small non-Heston wing bump (convex in log-moneyness, decaying with tau) so
            # the offline "market" is not exactly Heston: calibration lands at a realistic
            # sub-3% error and the residual model has genuine structure to correct.
            lm = np.log(k / forward)
            bump = perturb * (lm / 0.20) ** 2 / (1.0 + 2.0 * tau)
            iv = float(base_iv + bump) if np.isfinite(base_iv) else base_iv
            mid = (
                bs_price(spot, float(k), rate, div_yield, float(tau), iv, otype)
                if np.isfinite(iv)
                else heston_p
            )
            mid = max(mid, 1e-6)
            bid = mid * (1.0 - half_spread)
            ask = mid * (1.0 + half_spread)
            # Open interest / volume thin out for deep OTM and long maturities.
            depth = np.exp(-3.0 * abs(np.log(k / forward)))
            oi = float(max(0, int(5000 * depth + rng.integers(0, 50))))
            vol = float(max(0, int(1500 * depth + rng.integers(0, 30))))
            rows.append(
                {
                    "expiry": expiry,
                    "maturity": float(tau),
                    "strike": float(k),
                    "option_type": otype,
                    "bid": bid,
                    "ask": ask,
                    "mid": mid,
                    "last": mid,
                    "volume": vol,
                    "open_interest": oi,
                    "market_iv": iv,
                }
            )
    return pd.DataFrame(rows, columns=CHAIN_COLUMNS)


def synthetic_price_history(config: dict) -> pd.DataFrame:
    """Daily SPX-like history from a 3-state volatility-regime Markov chain.

    States 0/1/2 are calm / elevated / crisis with increasing annualised vol and
    decreasing drift, and high persistence (sticky regimes).  This is what lets the
    HMM later recover three *economically meaningful* regimes offline.  Returns a
    ``[close, volume]`` frame on a business-day index ending today.
    """
    syn = config["data"]["synthetic_fallback"]
    years = int(config["data"]["history_years"])
    rng = np.random.default_rng(int(syn["seed"]) + 1)

    n_days = years * 252
    # Annualised vol, annual drift, daily self-transition prob per regime.
    vols = np.array([0.10, 0.20, 0.45])
    drifts = np.array([0.12, 0.00, -0.30])
    stay = np.array([0.990, 0.965, 0.920])
    # Off-diagonal mass split toward the adjacent calmer/closer state.
    trans = np.array(
        [
            [stay[0], 1 - stay[0], 0.0],
            [(1 - stay[1]) * 0.6, stay[1], (1 - stay[1]) * 0.4],
            [0.0, 1 - stay[2], stay[2]],
        ]
    )

    states = np.empty(n_days, dtype=int)
    states[0] = 0
    for t in range(1, n_days):
        states[t] = rng.choice(3, p=trans[states[t - 1]])

    dt = 1.0 / 252.0
    daily_mu = drifts[states] * dt
    daily_sigma = vols[states] * np.sqrt(dt)
    log_ret = rng.normal(daily_mu - 0.5 * daily_sigma**2, daily_sigma)

    close = 500.0 * np.exp(np.cumsum(log_ret))
    # Volume: base level with crisis-driven spikes.
    base_vol = 3.0e9
    volume = base_vol * (1.0 + 0.5 * states) * np.exp(rng.normal(0.0, 0.15, n_days))

    end = pd.Timestamp(datetime.now().date())
    idx = pd.bdate_range(end=end, periods=n_days)
    df = pd.DataFrame({"close": close, "volume": volume}, index=idx)
    # Stash the latent regime + instantaneous vol so the synthetic VIX is consistent.
    df["_state"] = states
    df["_inst_vol"] = vols[states]
    return df


def synthetic_vix_term_structure(price_history: pd.DataFrame) -> pd.DataFrame:
    """A VIX term structure consistent with the synthetic price history's regimes.

    VIX ~ instantaneous vol x 100 plus noise.  Term structure is in contango (longer
    tenor richer) during calm regimes and backwardation during crises — the realistic
    sign flip the VIX slope feature keys on.
    """
    if "_inst_vol" not in price_history.columns:
        raise DataUnavailable("synthetic VIX requires a synthetic price history")
    rng = np.random.default_rng(99)
    inst = price_history["_inst_vol"].to_numpy()
    state = price_history["_state"].to_numpy()
    n = len(inst)

    vix = inst * 100.0 + rng.normal(0.0, 1.0, n)
    # Slope: +ve (contango) in calm, -ve (backwardation) in crisis.
    slope = np.where(state == 0, 2.5, np.where(state == 1, 0.5, -4.0))
    vix9d = np.clip(vix - 0.5 * slope + rng.normal(0, 0.5, n), 5.0, None)
    vix3m = np.clip(vix + slope + rng.normal(0, 0.5, n), 5.0, None)
    vix = np.clip(vix, 5.0, None)
    return pd.DataFrame({"vix9d": vix9d, "vix": vix, "vix3m": vix3m}, index=price_history.index)


# --------------------------------------------------------------------------- #
# Public wrappers: live-first, cache-friendly, synthetic last resort           #
# --------------------------------------------------------------------------- #


def get_price_history(config: dict, prefer_live: bool = True) -> FetchResult:
    """SPX daily history, live if reachable else synthetic (with provenance)."""
    ticker = config["data"]["spx_ticker"]
    years = int(config["data"]["history_years"])
    if prefer_live:
        try:
            df = _call_with_timeout(
                _request_timeout(config), fetch_price_history_live, ticker, years
            )
            return FetchResult(df, "live", _now(), ticker)
        except DataUnavailable:
            pass
    return FetchResult(synthetic_price_history(config), "synthetic", _now(), ticker)


def get_vix_term_structure(
    config: dict, price_history: pd.DataFrame | None = None, prefer_live: bool = True
) -> FetchResult:
    """VIX term structure, live if reachable else synthetic.

    The synthetic path needs the synthetic price history (to share its regimes), so
    pass ``price_history`` when you already have a synthetic one.
    """
    tickers = config["data"]["vix_tickers"]
    years = int(config["data"]["history_years"])
    if prefer_live:
        try:
            df = _call_with_timeout(
                _request_timeout(config), fetch_vix_term_structure_live, tickers, years
            )
            return FetchResult(df, "live", _now(), "VIX")
        except DataUnavailable:
            pass
    if price_history is None or "_inst_vol" not in price_history.columns:
        price_history = synthetic_price_history(config)
    return FetchResult(synthetic_vix_term_structure(price_history), "synthetic", _now(), "VIX")


def get_risk_free_rate(config: dict, prefer_live: bool = True) -> float:
    """Risk-free proxy: FRED if a key is configured, else the config constant."""
    if prefer_live:
        key = os.environ.get(config["data"].get("fred_api_key_env", "FRED_API_KEY"))
        try:
            return _call_with_timeout(
                _request_timeout(config),
                fetch_fred_rate_live,
                config["data"]["fred_rate_series"],
                key,
            )
        except DataUnavailable:
            pass
    return float(config["market"]["risk_free_rate"])


def get_market_snapshot(
    config: dict, prefer_live: bool = True, allow_synthetic: bool = True
) -> ChainSnapshot:
    """A full options snapshot (spot + rate + chain), live-first with fallback.

    Spot is the latest close from the price history; the rate is the FRED/config
    risk-free proxy; the options chain is the live yfinance chain or the synthetic
    Heston surface.  This is exactly what the calibration service needs.

    With ``allow_synthetic=False`` the chain *must* come from a live pull — any failure
    raises :class:`DataUnavailable` instead of synthesising.  The cache uses this to
    distinguish "live failed, serve stale/synthetic" from a genuine live result.
    """
    div_yield = float(config["market"]["dividend_yield"])
    rate = get_risk_free_rate(config, prefer_live=prefer_live)
    today = _now()

    if prefer_live:
        timeout = _request_timeout(config)
        try:
            spot = float(_call_with_timeout(timeout, fetch_spot_live, config["data"]["spx_ticker"]))
            max_expiries = int(config["data"].get("max_option_expiries", 4))
            target_days = tuple(
                int(day)
                for day in config["data"].get("option_expiry_target_days", [30, 90, 180, 365])
            )
            chain = _call_with_timeout(
                timeout,
                fetch_options_chain_live,
                config["data"]["options_underlying"],
                spot,
                rate,
                div_yield,
                today,
                max_expiries,
                target_days,
            )
            if chain.empty:
                raise DataUnavailable("live chain empty")
            return ChainSnapshot(spot, rate, div_yield, chain, "live", today)
        except DataUnavailable:
            if not allow_synthetic:
                raise
    elif not allow_synthetic:
        raise DataUnavailable("live data disabled but synthetic not allowed")

    # Synthetic fallback uses a clean SPX-like spot so the surface is well-scaled.
    syn_spot = float(config["data"]["synthetic_fallback"]["spot"])
    chain = synthetic_options_chain(config, syn_spot, rate, div_yield, today)
    return ChainSnapshot(syn_spot, rate, div_yield, chain, "synthetic", today)


# --------------------------------------------------------------------------- #
# Liquidity filtering                                                          #
# --------------------------------------------------------------------------- #


def _bs_abs_delta(
    spot: float,
    strike: float,
    rate: float,
    div_yield: float,
    tau: float,
    sigma: float,
    option_type: str,
) -> float:
    """|Black-Scholes delta| from market IV, for the deep-OTM cut."""
    from scipy.stats import norm

    if not np.isfinite(sigma) or sigma <= 0 or tau <= 0:
        return 0.0
    d1 = (np.log(spot / strike) + (rate - div_yield + 0.5 * sigma**2) * tau) / (
        sigma * np.sqrt(tau)
    )
    call_delta = np.exp(-div_yield * tau) * norm.cdf(d1)
    delta = call_delta if option_type == "call" else call_delta - np.exp(-div_yield * tau)
    return float(abs(delta))


def filter_liquid_options(
    snapshot: ChainSnapshot, config: dict
) -> tuple[pd.DataFrame, LiquidityReport]:
    """Drop illiquid / unusable quotes and report what was removed and why.

    Filters (config ``data.liquidity``):
      * no recoverable market IV (price below intrinsic or non-invertible),
      * very short maturity (microstructure noise dominates),
      * zero open interest,
      * bid-ask spread wider than ``max_rel_spread`` of the mid,
      * deep OTM with ``|delta| < min_delta``.
    """
    liq = config["data"]["liquidity"]
    df = snapshot.chain.copy()
    n_input = len(df)
    rep = LiquidityReport(n_input=n_input, n_kept=0)

    # No usable implied vol.
    bad_iv = ~np.isfinite(df["market_iv"]) | (df["market_iv"] <= 0)
    rep.removed_no_iv = int(bad_iv.sum())
    df = df[~bad_iv]

    # Short maturity.
    min_tau = float(liq["min_maturity_days"]) / 365.0
    short = df["maturity"] < min_tau
    rep.removed_short_maturity = int(short.sum())
    df = df[~short]

    # Zero open interest.
    zero_oi = df["open_interest"] < float(liq["min_open_interest"])
    rep.removed_zero_oi = int(zero_oi.sum())
    df = df[~zero_oi]

    # Wide relative spread (only where both bid/ask are present).
    rel_spread = (df["ask"] - df["bid"]) / df["mid"].replace(0, np.nan)
    wide = rel_spread.gt(float(liq["max_rel_spread"])).fillna(False)
    rep.removed_wide_spread = int(wide.sum())
    df = df[~wide]

    # Deep OTM by delta.
    deltas = (
        np.array(
            [
                _bs_abs_delta(snapshot.spot, k, snapshot.rate, snapshot.div_yield, t, iv, ot)
                for k, t, iv, ot in zip(
                    df["strike"], df["maturity"], df["market_iv"], df["option_type"]
                )
            ]
        )
        if len(df)
        else np.array([])
    )
    deep = deltas < float(liq["min_delta"]) if len(df) else np.array([], dtype=bool)
    rep.removed_deep_otm = int(deep.sum())
    df = df[~deep] if len(df) else df

    df = df.reset_index(drop=True)
    rep.n_kept = len(df)
    return df, rep
